name: Benchmark

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev
        cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Run benchmarks
      working-directory: ${{github.workspace}}/build/benchmarks
      run: ./benchmarks
